spring.application.name=backtest

# application.properties
spring.datasource.url=jdbc:mysql://localhost:3306/trading_db
spring.datasource.username=root
spring.datasource.password=Test
spring.datasource.driver-class=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
